/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vistas.cliente;

import controladores.ControladorCliente;
import controladores.ControladorConcurso;
import javax.swing.table.DefaultTableModel;
import modelos.Concurso;
import util.Lista;

/**
 *
 * @author Asus
 */
public class ConcursosVigentes extends javax.swing.JPanel {
ControladorCliente controlador;
    ControladorConcurso controladorC;
    private DefaultTableModel mode;

    public ConcursosVigentes(ControladorConcurso controladorC,ControladorCliente controlador) {
        initComponents();
        this.controladorC = controladorC;
        this.controlador = controlador;
        mode = new DefaultTableModel();

        this.tablaConcursos.setModel(mode);
        mode.addColumn("ID");
        mode.addColumn("FECHA INICIO");
        mode.addColumn("FECHA FINAL");
        mode.addColumn("CONSUMO MINIMO");
        mode.addColumn("PREMIO");
        limpiar();
    }
    
    public void limpiar() {
      
     
        removerTablacConcurso();
        llenarTablaConcurso();

        
    }

     public void removerTablacConcurso() {

        for (int i = 0; i < mode.getRowCount(); i++) {
            mode.removeRow(i);
        }

    }

       public void limpiarFiltroConcurso() {
        removerTablacConcurso();
        llenarTablaConcurso();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablaConcursos = new javax.swing.JTable();
        comboConcurso = new javax.swing.JComboBox<>();

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        tablaConcursos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(tablaConcursos);

        comboConcurso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TODOS", "EN PARTICIPACION" }));
        comboConcurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboConcursoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 669, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(comboConcurso, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(comboConcurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 895, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 593, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void comboConcursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboConcursoActionPerformed
        limpiarFiltroConcurso();
    }//GEN-LAST:event_comboConcursoActionPerformed
public void llenarTablaConcurso() {
        if (comboConcurso.getSelectedIndex() == 0) {
            removerTablacConcurso();
            Lista<Concurso> concursos = controladorC.getConcursos();
            for (int i = 0; i < concursos.Size(); i++) {
                Concurso concurso = concursos.obtener(i);

                String[] info = new String[5];
                info[0] = String.valueOf(concurso.getNumeroConcurso());
                info[1] = String.valueOf(concurso.getFechaInicio());
                info[2] = String.valueOf(concurso.getFechaFinal());
                info[3] = String.valueOf(concurso.getValorMinimo());
                info[4] = String.valueOf(concurso.getDetalleConcurso());

                mode.addRow(info);

            }
        } else {
            removerTablacConcurso();
            Lista<Concurso> concursos = controladorC.obtenerConcursosPorCliente(controlador.getCliente());
            for (int i = 0; i < concursos.Size(); i++) {
                Concurso concurso = concursos.obtener(i);

                String[] info = new String[5];

                info[0] = String.valueOf(concurso.getNumeroConcurso());
                info[1] = String.valueOf(concurso.getFechaInicio());
                info[2] = String.valueOf(concurso.getFechaFinal());
                info[3] = String.valueOf(concurso.getValorMinimo());
                info[4] = String.valueOf(concurso.getDetalleConcurso());

                mode.addRow(info);

            }
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboConcurso;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable tablaConcursos;
    // End of variables declaration//GEN-END:variables
}
