/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vistas.cliente;

import controladores.ControladorCliente;
import javax.swing.table.DefaultTableModel;
import modelos.Venta;
import util.Lista;

/**
 *
 * @author Asus
 */
public class HistorialCliente extends javax.swing.JPanel {

    private DefaultTableModel modell;
    ControladorCliente controlador;

    public HistorialCliente(ControladorCliente controlador) {
        initComponents();
        this.controlador = controlador;
        modell = new DefaultTableModel();

        this.tablaHistorial.setModel(modell);
        modell.addColumn("No. Articulos");
        modell.addColumn("Fecha");
        modell.addColumn("Valor total");
        limpiar();
    }

    public void removerTablaHistorial() {

        for (int i = 0; i < modell.getRowCount(); i++) {
            modell.removeRow(i);
        }

    }

    public void limpiar() {

        removerTablaHistorial();
        llenarTablaHistorial();
    }

    public void llenarTablaHistorial() {
        removerTablaHistorial();
        Lista<Venta> historial = controlador.getHistorialCliente();
        for (int i = 0; i < historial.Size(); i++) {
            Venta venta = historial.obtener(i);
            if (venta != null) {
                String[] info = new String[4];
                info[0] = String.valueOf(venta.getCompra().getArticulos());
                info[1] = venta.getFechaVenta().toString();
                info[2] = String.valueOf(venta.getTotalCompra());

                modell.addRow(info);

                txtTotalnvertido.setText(String.valueOf(controlador.getCliente().getTotalInvertido()));

            } else {

            }

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBotones2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaHistorial = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        txtTotalnvertido = new javax.swing.JTextField();

        panelBotones2.setBackground(new java.awt.Color(255, 255, 255));

        tablaHistorial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tablaHistorial);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("TOTAL INVERITIDO :  $");

        txtTotalnvertido.setBackground(new java.awt.Color(255, 255, 255));
        txtTotalnvertido.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        txtTotalnvertido.setForeground(new java.awt.Color(0, 0, 0));
        txtTotalnvertido.setBorder(null);

        javax.swing.GroupLayout panelBotones2Layout = new javax.swing.GroupLayout(panelBotones2);
        panelBotones2.setLayout(panelBotones2Layout);
        panelBotones2Layout.setHorizontalGroup(
            panelBotones2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotones2Layout.createSequentialGroup()
                .addGroup(panelBotones2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBotones2Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 777, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelBotones2Layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTotalnvertido, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        panelBotones2Layout.setVerticalGroup(
            panelBotones2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotones2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panelBotones2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBotones2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel9))
                    .addGroup(panelBotones2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtTotalnvertido, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 895, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelBotones2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 593, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelBotones2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel panelBotones2;
    private javax.swing.JTable tablaHistorial;
    private javax.swing.JTextField txtTotalnvertido;
    // End of variables declaration//GEN-END:variables
}
