/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vistas.adminLocal;

import controladores.ControladorSeparados;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelos.Cliente;
import modelos.Local;
import modelos.Multa;
import modelos.Producto;
import modelos.Separado;
import util.Lista;

/**
 *
 * @author Asus
 */
public class SeparadosNuevo extends javax.swing.JPanel {

    ControladorSeparados controlador;
    private DefaultTableModel model;
    Local local;

    public SeparadosNuevo(Local local) {
        initComponents();
        model = new DefaultTableModel();
        txtArea.setVisible(false);
        btnAsignar.setVisible(false);

        this.local = local;
        controlador = new ControladorSeparados(local);
        this.tablaSeparados.setModel(model);
        model.addColumn("ID PRODUCTO");
        model.addColumn("NOMBRE PRODUCTO");
        model.addColumn("CC DEL CLIENTE");
        model.addColumn("FECHA DE ENTREGA");
        limpiar();

    }

    public void llenarTabla() {
        remover();
        Lista<Separado> separados = controlador.getSeparados();
        for (int i = 0; i < separados.Size(); i++) {
            Separado venta = separados.obtener(i);
            if (venta != null) {
                Producto producto = venta.getProducto();
                String[] info = new String[5];
                info[0] = String.valueOf(producto.getIdentificador());
                info[1] = String.valueOf(producto.getNombreProducto());

                info[2] = String.valueOf(venta.getCliente().getDocumento());
                info[3] = String.valueOf(venta.getFechaEntrega());

                model.addRow(info);

            } else {

            }

        }
    }

    public void limpiar() {
        remover();
        llenarTabla();
    }

    public void remover() {

        for (int i = 0; i < model.getRowCount(); i++) {
            model.removeRow(i);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaSeparados = new javax.swing.JTable();
        btnFinalizarSeparado = new javax.swing.JButton();
        btnGenerarMulta = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();
        btnAsignar = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1073, 509));

        tablaSeparados.setBackground(new java.awt.Color(255, 255, 0));
        tablaSeparados.setForeground(new java.awt.Color(0, 0, 0));
        tablaSeparados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaSeparados);

        btnFinalizarSeparado.setBackground(new java.awt.Color(0, 153, 153));
        btnFinalizarSeparado.setForeground(new java.awt.Color(255, 255, 255));
        btnFinalizarSeparado.setText("FINALIZAR SEPARADO");
        btnFinalizarSeparado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarSeparadoActionPerformed(evt);
            }
        });

        btnGenerarMulta.setBackground(new java.awt.Color(0, 153, 153));
        btnGenerarMulta.setForeground(new java.awt.Color(255, 255, 255));
        btnGenerarMulta.setText("GENERAR MULTA");
        btnGenerarMulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarMultaActionPerformed(evt);
            }
        });

        txtArea.setColumns(20);
        txtArea.setRows(5);
        txtArea.setBorder(null);
        jScrollPane2.setViewportView(txtArea);

        btnAsignar.setBackground(new java.awt.Color(0, 153, 153));
        btnAsignar.setForeground(new java.awt.Color(255, 255, 255));
        btnAsignar.setText("ASIGNAR MULTA");
        btnAsignar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsignarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 623, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnGenerarMulta, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnFinalizarSeparado, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(btnAsignar)))
                .addContainerGap(127, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(btnFinalizarSeparado, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69)
                        .addComponent(btnGenerarMulta, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAsignar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnFinalizarSeparadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarSeparadoActionPerformed
        if (tablaSeparados.getSelectionModel().isSelectionEmpty()) {
            JOptionPane.showMessageDialog(null, "Seleccione el separado que desea finalizar");
        } else {
            int fila = tablaSeparados.getSelectedRow();
            String documento = tablaSeparados.getValueAt(fila, 2).toString();
            Separado separado = controlador.buscarSeparado(documento);
            boolean aux = controlador.FinalizarSeparado(separado);
            if (aux) {
                JOptionPane.showMessageDialog(null, "Se ha finalizado con éxito el separado");
                limpiar();
            } else {
                JOptionPane.showMessageDialog(null, "No se ha podido finalizar");
            }

        }

    }//GEN-LAST:event_btnFinalizarSeparadoActionPerformed

    private void btnGenerarMultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarMultaActionPerformed
        txtArea.setVisible(true);
        btnAsignar.setVisible(true);

    }//GEN-LAST:event_btnGenerarMultaActionPerformed

    private void btnAsignarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsignarActionPerformed
        if (tablaSeparados.getSelectionModel().isSelectionEmpty()) {
            JOptionPane.showMessageDialog(null, "Seleccione el separado al que desea generar multa");
        } else if (txtArea.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ingrese el detalle del porqué de la multa");
        } else {
            int fila = tablaSeparados.getSelectedRow();
            String documento = tablaSeparados.getValueAt(fila, 2).toString();
            String detalle = txtArea.getText();
            Separado separado = controlador.buscarSeparado(documento);
            Cliente cliente = controlador.buscarCliente(documento);
            Multa multa = new Multa(detalle, cliente);
            boolean aux = controlador.asignarMulta(multa, separado);
            if (aux) {
                JOptionPane.showMessageDialog(null, "Se ha asignado con éxito la multa");
                limpiar();
            } else {
                JOptionPane.showMessageDialog(null, "No se ha podido finalizar");
            }

        }
    }//GEN-LAST:event_btnAsignarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAsignar;
    private javax.swing.JButton btnFinalizarSeparado;
    private javax.swing.JButton btnGenerarMulta;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tablaSeparados;
    private javax.swing.JTextArea txtArea;
    // End of variables declaration//GEN-END:variables
}
