/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas.administrador;

import ValidarCampos.ValidarCampos;
import controladores.ControladorCasilla;
import controladores.ControladorConcurso;
import controladores.ControladorUsuario;
import excepciones.CorreoExistenteException;
import excepciones.TelefonoInvalidoException;
import excepciones.UsuarioExistenteException;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Date;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

import modelos.Administrador;

import modelos.Casilla;
import modelos.Cliente;
import modelos.Concurso;
import modelos.Empleado;
import modelos.Usuario;
import util.Lista;
import vistas.InicioSesion;

/**
 *
 * @author Asus
 */
public class AdministradorGeneral extends javax.swing.JFrame {

    JButton[][] botones;
    ControladorCasilla controlador;
    Administrador admin;
    ControladorUsuario controladorU;
    ControladorConcurso controladorC;

    public AdministradorGeneral(Administrador administrador) {
        initComponents();
        setLocationRelativeTo(this);

        setResizable(false);
        admin = administrador;
        lblNombre.setText(admin.getNombre() + "(Administrador)");

        controladorU = new ControladorUsuario();

        ///////////////////////////////////////
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnSolicitudes = new javax.swing.JButton();
        locales = new javax.swing.JButton();
        gestionClientes = new javax.swing.JButton();
        gestionEmpleados = new javax.swing.JButton();
        concursos1 = new javax.swing.JButton();
        btnSolicitudes1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblNombre = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        content = new javax.swing.JPanel();

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(0, 153, 153));
        jPanel6.setPreferredSize(new java.awt.Dimension(1048, 70));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1042, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 0, 1042, 70));

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSolicitudes.setBackground(new java.awt.Color(0, 153, 153));
        btnSolicitudes.setForeground(new java.awt.Color(255, 255, 255));
        btnSolicitudes.setText("MAS VENTAS");
        btnSolicitudes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSolicitudes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSolicitudesMouseClicked(evt);
            }
        });
        btnSolicitudes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSolicitudesActionPerformed(evt);
            }
        });
        jPanel1.add(btnSolicitudes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 200, 45));

        locales.setBackground(new java.awt.Color(0, 153, 153));
        locales.setForeground(new java.awt.Color(255, 255, 255));
        locales.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/economia-local (1).png"))); // NOI18N
        locales.setText("LOCALES");
        locales.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        locales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                localesMouseClicked(evt);
            }
        });
        locales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                localesActionPerformed(evt);
            }
        });
        jPanel1.add(locales, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 200, 45));

        gestionClientes.setBackground(new java.awt.Color(0, 153, 153));
        gestionClientes.setForeground(new java.awt.Color(255, 255, 255));
        gestionClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/clasificacion (1).png"))); // NOI18N
        gestionClientes.setText("GESTION CLIENTES");
        gestionClientes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        gestionClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gestionClientesMouseClicked(evt);
            }
        });
        gestionClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestionClientesActionPerformed(evt);
            }
        });
        jPanel1.add(gestionClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 200, 45));

        gestionEmpleados.setBackground(new java.awt.Color(0, 153, 153));
        gestionEmpleados.setForeground(new java.awt.Color(255, 255, 255));
        gestionEmpleados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/empleado (1).png"))); // NOI18N
        gestionEmpleados.setText("GESTION EMPLEADOS");
        gestionEmpleados.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        gestionEmpleados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gestionEmpleadosMouseClicked(evt);
            }
        });
        gestionEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestionEmpleadosActionPerformed(evt);
            }
        });
        jPanel1.add(gestionEmpleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 200, 45));

        concursos1.setBackground(new java.awt.Color(0, 153, 153));
        concursos1.setForeground(new java.awt.Color(255, 255, 255));
        concursos1.setText("CONCURSOS");
        concursos1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        concursos1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                concursos1MouseClicked(evt);
            }
        });
        concursos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                concursos1ActionPerformed(evt);
            }
        });
        jPanel1.add(concursos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 200, 45));

        btnSolicitudes1.setBackground(new java.awt.Color(0, 153, 153));
        btnSolicitudes1.setForeground(new java.awt.Color(255, 255, 255));
        btnSolicitudes1.setText("SOLICITUDES");
        btnSolicitudes1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSolicitudes1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSolicitudes1MouseClicked(evt);
            }
        });
        btnSolicitudes1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSolicitudes1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnSolicitudes1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 200, 45));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 231, 200, 439));

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNombre.setForeground(new java.awt.Color(255, 255, 255));
        lblNombre.setText("Name");
        jPanel2.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vistas/administrador/punto verde.jpg"))); // NOI18N
        jLabel2.setText("Conectado");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 90, -1));

        btnRegresar.setBackground(new java.awt.Color(204, 0, 51));
        btnRegresar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegresar.setText("CERRRAR SESIÓN");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        jPanel2.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/perfil (1).png"))); // NOI18N
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 236));

        content.setBackground(new java.awt.Color(255, 255, 255));
        content.setForeground(new java.awt.Color(255, 255, 255));
        content.setPreferredSize(new java.awt.Dimension(1048, 598));

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1040, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        getContentPane().add(content, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 1040, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        InicioSesion ventana = new InicioSesion();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnSolicitudesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSolicitudesActionPerformed
        MasVentas gestion = new MasVentas();
        showPanel(gestion);
    }//GEN-LAST:event_btnSolicitudesActionPerformed

    private void btnSolicitudesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSolicitudesMouseClicked
        /*Local local = new Local();
        showPanel(local);*/
    }//GEN-LAST:event_btnSolicitudesMouseClicked

    private void localesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_localesMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_localesMouseClicked

    private void localesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_localesActionPerformed
        Locales local = new Locales();
        showPanel(local);
    }//GEN-LAST:event_localesActionPerformed

    private void gestionClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gestionClientesMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_gestionClientesMouseClicked

    private void gestionClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestionClientesActionPerformed
        GestionCliente gestion = new GestionCliente();
        showPanel(gestion);
    }//GEN-LAST:event_gestionClientesActionPerformed

    private void gestionEmpleadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gestionEmpleadosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_gestionEmpleadosMouseClicked

    private void gestionEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestionEmpleadosActionPerformed
        GestionEmpleado gestion = new GestionEmpleado();
        showPanel(gestion);
    }//GEN-LAST:event_gestionEmpleadosActionPerformed

    private void concursos1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_concursos1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_concursos1MouseClicked

    private void concursos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_concursos1ActionPerformed
      Concursos concu = new Concursos();
        showPanel(concu);
    }//GEN-LAST:event_concursos1ActionPerformed

    private void btnSolicitudes1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSolicitudes1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSolicitudes1MouseClicked

    private void btnSolicitudes1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSolicitudes1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSolicitudes1ActionPerformed

    public Administrador getAdmin() {
        return admin;
    }

    public void showPanel(JPanel panel) {
        panel.setSize(1047, 598);
        panel.setLocation(0, 0);
        content.removeAll();
        content.add(panel, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnSolicitudes;
    private javax.swing.JButton btnSolicitudes1;
    private javax.swing.JButton concursos1;
    private javax.swing.JPanel content;
    private javax.swing.JButton gestionClientes;
    private javax.swing.JButton gestionEmpleados;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JButton locales;
    // End of variables declaration//GEN-END:variables
}
