/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vistas.administrador;

import ValidarCampos.ValidarCampos;
import controladores.ControladorUsuario;
import excepciones.CorreoExistenteException;
import excepciones.TelefonoInvalidoException;
import excepciones.UsuarioExistenteException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelos.Cliente;
import modelos.Usuario;
import util.Lista;
import util.Pila;

public class GestionCliente extends javax.swing.JPanel {

    ControladorUsuario controladorU;
    private DefaultTableModel modelo;
    Pila<Cliente> pilaZ;
    Pila<Cliente> pilaY;

    public GestionCliente() {
        initComponents();

        controladorU = new ControladorUsuario();
        modelo = new DefaultTableModel();
        this.tablaClientes.setModel(modelo);
        pilaZ = new Pila<>();
        pilaY = new Pila<>();
        modelo.addColumn("Nombre");
        modelo.addColumn("Documento");
        modelo.addColumn("Correo");
        modelo.addColumn("Telefono");
        limpiar();
    }

    public void llenarTablaClientes() {
        removerTabla();
        Lista<Usuario> usuarios = controladorU.getUsuarios();
        for (int i = 0; i < usuarios.Size(); i++) {
            Usuario cliente = usuarios.obtener(i);
            if (cliente != null && cliente instanceof Cliente) {
                String[] info = new String[4];
                info[0] = cliente.getNombre();
                info[1] = cliente.getDocumento();
                info[2] = cliente.getCorreo();
                info[3] = cliente.getTelefono();

                modelo.addRow(info);

            } else {

            }

        }
    }

    public void removerTabla() {
        for (int i = 0; i < modelo.getRowCount(); i++) {
            modelo.removeRow(i);
        }

    }

    public void limpiar() {
        txtDocumento5.setText("");
        txtNombre5.setText("");
        txtTelefono5.setText("");
        txtApellido5.setText("");
        txtCorreo5.setText("");
        txtContra5.setText("");
        txtDireccion5.setText("");
        comboSexo5.setSelectedIndex(0);
        removerTabla();
        txtDocumento5.setEditable(true);
        llenarTablaClientes();
        ///////////////////////////////

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel63 = new javax.swing.JLabel();
        txtNombre5 = new javax.swing.JTextField();
        jLabel64 = new javax.swing.JLabel();
        txtApellido5 = new javax.swing.JTextField();
        jLabel65 = new javax.swing.JLabel();
        txtDocumento5 = new javax.swing.JTextField();
        jLabel66 = new javax.swing.JLabel();
        txtTelefono5 = new javax.swing.JTextField();
        comboSexo5 = new javax.swing.JComboBox<>();
        jLabel67 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        txtCorreo5 = new javax.swing.JTextField();
        jLabel70 = new javax.swing.JLabel();
        txtContra5 = new javax.swing.JTextField();
        jLabel71 = new javax.swing.JLabel();
        txtDireccion5 = new javax.swing.JTextField();
        btnRegistrar5 = new javax.swing.JButton();
        btnEditar5 = new javax.swing.JButton();
        btnEliminar5 = new javax.swing.JButton();
        jLabel73 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        btnBuscar4 = new javax.swing.JButton();
        txtDocuEliminar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaClientes = new javax.swing.JTable();
        jLabel74 = new javax.swing.JLabel();
        jLabel85 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jSeparator15 = new javax.swing.JSeparator();
        jSeparator16 = new javax.swing.JSeparator();
        jSeparator17 = new javax.swing.JSeparator();
        jSeparator18 = new javax.swing.JSeparator();
        jSeparator19 = new javax.swing.JSeparator();
        jSeparator20 = new javax.swing.JSeparator();
        jSeparator21 = new javax.swing.JSeparator();
        txtCorrAdicional1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setMinimumSize(new java.awt.Dimension(1048, 598));
        jPanel4.setPreferredSize(new java.awt.Dimension(1047, 598));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel63.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        jLabel63.setForeground(new java.awt.Color(0, 0, 0));
        jLabel63.setText("Nombre:");
        jPanel4.add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 69, -1, -1));

        txtNombre5.setBorder(null);
        txtNombre5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombre5KeyTyped(evt);
            }
        });
        jPanel4.add(txtNombre5, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 90, 214, -1));

        jLabel64.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        jLabel64.setForeground(new java.awt.Color(0, 0, 0));
        jLabel64.setText("Apellido:");
        jPanel4.add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 127, -1, -1));

        txtApellido5.setBorder(null);
        txtApellido5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellido5KeyTyped(evt);
            }
        });
        jPanel4.add(txtApellido5, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 148, 214, -1));

        jLabel65.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        jLabel65.setForeground(new java.awt.Color(0, 0, 0));
        jLabel65.setText("Documento:");
        jPanel4.add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 182, -1, -1));

        txtDocumento5.setBorder(null);
        txtDocumento5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDocumento5ActionPerformed(evt);
            }
        });
        txtDocumento5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDocumento5KeyTyped(evt);
            }
        });
        jPanel4.add(txtDocumento5, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 203, 214, -1));

        jLabel66.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        jLabel66.setForeground(new java.awt.Color(0, 0, 0));
        jLabel66.setText("Telefono:");
        jPanel4.add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 238, -1, -1));

        txtTelefono5.setBorder(null);
        txtTelefono5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefono5KeyTyped(evt);
            }
        });
        jPanel4.add(txtTelefono5, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 259, 214, -1));

        comboSexo5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione ", "Masculino", "Femenino", "No especifica" }));
        comboSexo5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboSexo5ActionPerformed(evt);
            }
        });
        jPanel4.add(comboSexo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 314, 214, -1));

        jLabel67.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        jLabel67.setForeground(new java.awt.Color(0, 0, 0));
        jLabel67.setText("Sexo:");
        jPanel4.add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 293, -1, -1));

        jLabel69.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        jLabel69.setForeground(new java.awt.Color(0, 0, 0));
        jLabel69.setText("Correo:");
        jPanel4.add(jLabel69, new org.netbeans.lib.awtextra.AbsoluteConstraints(316, 127, -1, -1));

        txtCorreo5.setBorder(null);
        jPanel4.add(txtCorreo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(316, 148, 137, -1));

        jLabel70.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        jLabel70.setForeground(new java.awt.Color(0, 0, 0));
        jLabel70.setText("Contraseña:");
        jPanel4.add(jLabel70, new org.netbeans.lib.awtextra.AbsoluteConstraints(316, 182, -1, -1));

        txtContra5.setBorder(null);
        jPanel4.add(txtContra5, new org.netbeans.lib.awtextra.AbsoluteConstraints(316, 203, 216, -1));

        jLabel71.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        jLabel71.setForeground(new java.awt.Color(0, 0, 0));
        jLabel71.setText("Direccion:");
        jPanel4.add(jLabel71, new org.netbeans.lib.awtextra.AbsoluteConstraints(316, 238, -1, -1));

        txtDireccion5.setBorder(null);
        jPanel4.add(txtDireccion5, new org.netbeans.lib.awtextra.AbsoluteConstraints(316, 259, 216, -1));

        btnRegistrar5.setBackground(new java.awt.Color(0, 153, 153));
        btnRegistrar5.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrar5.setText("REGISTRAR");
        btnRegistrar5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrar5ActionPerformed(evt);
            }
        });
        jPanel4.add(btnRegistrar5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 376, 174, -1));

        btnEditar5.setBackground(new java.awt.Color(0, 153, 153));
        btnEditar5.setForeground(new java.awt.Color(255, 255, 255));
        btnEditar5.setText("EDITAR");
        btnEditar5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditar5ActionPerformed(evt);
            }
        });
        jPanel4.add(btnEditar5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 410, 174, -1));

        btnEliminar5.setBackground(new java.awt.Color(0, 153, 153));
        btnEliminar5.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar5.setText("ELIMINAR ");
        btnEliminar5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminar5ActionPerformed(evt);
            }
        });
        jPanel4.add(btnEliminar5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 444, 174, -1));

        jLabel73.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jLabel73.setForeground(new java.awt.Color(0, 0, 0));
        jLabel73.setText("GESTIÓN DE CLIENTES");
        jPanel4.add(jLabel73, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 28, -1, 23));

        jPanel16.setBackground(new java.awt.Color(0, 153, 153));
        jPanel16.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        btnBuscar4.setBackground(new java.awt.Color(255, 255, 255));
        btnBuscar4.setForeground(new java.awt.Color(0, 0, 0));
        btnBuscar4.setText("BUSCAR");
        btnBuscar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscar4ActionPerformed(evt);
            }
        });

        txtDocuEliminar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDocuEliminarKeyTyped(evt);
            }
        });

        tablaClientes.setBackground(new java.awt.Color(255, 255, 51));
        tablaClientes.setForeground(new java.awt.Color(0, 0, 0));
        tablaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaClientes);

        jLabel74.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel74.setForeground(new java.awt.Color(255, 255, 255));
        jLabel74.setText("CLIENTES REGISTRADOS");

        jLabel85.setForeground(new java.awt.Color(255, 255, 255));
        jLabel85.setText("INGRESE EL DOCUMENTO A BUSCAR :");

        jButton2.setText("CONTROL Z");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("CONTROL Y");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(txtDocuEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addGap(209, 209, 209)
                        .addComponent(btnBuscar4, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(jLabel85))
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(jLabel74)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                .addGap(0, 22, Short.MAX_VALUE)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addGap(36, 36, 36)
                        .addComponent(jButton2)
                        .addGap(34, 34, 34))))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel74)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel85)
                .addGap(18, 18, 18)
                .addComponent(txtDocuEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnBuscar4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 132, Short.MAX_VALUE)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(33, 33, 33))
        );

        jPanel4.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(548, -7, 500, 610));
        jPanel4.add(jSeparator15, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 166, 208, 10));
        jPanel4.add(jSeparator16, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 222, 217, 10));
        jPanel4.add(jSeparator17, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 277, 217, 10));
        jPanel4.add(jSeparator18, new org.netbeans.lib.awtextra.AbsoluteConstraints(316, 222, 217, 10));
        jPanel4.add(jSeparator19, new org.netbeans.lib.awtextra.AbsoluteConstraints(316, 166, 217, 10));
        jPanel4.add(jSeparator20, new org.netbeans.lib.awtextra.AbsoluteConstraints(316, 277, 217, 10));
        jPanel4.add(jSeparator21, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 111, 217, 10));

        txtCorrAdicional1.setBackground(new java.awt.Color(255, 255, 255));
        txtCorrAdicional1.setForeground(new java.awt.Color(0, 0, 0));
        txtCorrAdicional1.setText("@cliente.com");
        txtCorrAdicional1.setBorder(null);
        txtCorrAdicional1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorrAdicional1ActionPerformed(evt);
            }
        });
        jPanel4.add(txtCorrAdicional1, new org.netbeans.lib.awtextra.AbsoluteConstraints(459, 148, -1, -1));

        jButton1.setBackground(new java.awt.Color(255, 51, 51));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("LIMPIAR CAMPOS");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 560, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 1048, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombre5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombre5KeyTyped
        new ValidarCampos().validarLetras(evt);
    }//GEN-LAST:event_txtNombre5KeyTyped

    private void txtApellido5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellido5KeyTyped
        new ValidarCampos().validarLetras(evt);
    }//GEN-LAST:event_txtApellido5KeyTyped

    private void txtDocumento5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDocumento5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDocumento5ActionPerformed

    private void txtDocumento5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDocumento5KeyTyped
        new ValidarCampos().validarNumeros(evt);
    }//GEN-LAST:event_txtDocumento5KeyTyped

    private void txtTelefono5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefono5KeyTyped
        new ValidarCampos().validarNumeros(evt);
    }//GEN-LAST:event_txtTelefono5KeyTyped

    private void comboSexo5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboSexo5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboSexo5ActionPerformed

    private void btnRegistrar5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrar5ActionPerformed
        if (txtNombre5.getText().isEmpty() || txtDocumento5.getText().isEmpty() || txtTelefono5.getText().isEmpty() || comboSexo5.getSelectedIndex() == 0
                || txtCorreo5.getText().isEmpty() || txtTelefono5.getText().isEmpty() || txtDireccion5.getText().isEmpty() || txtContra5.getText().isEmpty()) {

            JOptionPane.showMessageDialog(null, "Todos los campos son obligatorios");

        } else {
            String nombre = txtNombre5.getText();
            String documento = txtDocumento5.getText();
            String telefono = txtTelefono5.getText();
            String correo = txtCorreo5.getText() + txtCorrAdicional1.getText();
            String contraseña = txtContra5.getText();
            String sexo = comboSexo5.getSelectedItem().toString();
            String apellido = txtApellido5.getText();
            String direccion = txtDireccion5.getText();
            String adicional = txtCorrAdicional1.getText();
            Usuario cliente = new Cliente(nombre, documento, telefono, correo, contraseña, apellido, direccion, sexo);

            try {
                controladorU.registrarUsuario(cliente, adicional);
                Cliente client = (Cliente) cliente;
                pilaZ.push(client);
                JOptionPane.showMessageDialog(null, "El cliente " + cliente.getNombre() + " se ha registrado con éxito");
                limpiar();

            } catch (UsuarioExistenteException | TelefonoInvalidoException | CorreoExistenteException ex) {
                ex.getMessage();
            }
        }
    }//GEN-LAST:event_btnRegistrar5ActionPerformed

    private void btnEditar5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditar5ActionPerformed
        if (txtNombre5.getText().isEmpty() || txtDocumento5.getText().isEmpty() || txtTelefono5.getText().isEmpty() || comboSexo5.getSelectedIndex() == 0
                || txtCorreo5.getText().isEmpty() || txtTelefono5.getText().isEmpty() || txtDireccion5.getText().isEmpty() || txtContra5.getText().isEmpty()) {

            JOptionPane.showMessageDialog(null, "Todos los campos son obligatorios");

        } else {
            String nombre = txtNombre5.getText();
            String documento = txtDocumento5.getText();
            String telefono = txtTelefono5.getText();
            String correo = txtCorreo5.getText();
            String contraseña = txtContra5.getText();
            String sexo = comboSexo5.getSelectedItem().toString();

            String apellido = txtApellido5.getText();
            String direccion = txtDireccion5.getText();

            Usuario cliente = new Cliente(nombre, documento, telefono, correo, contraseña, apellido, direccion, sexo);
            boolean es = controladorU.editarUsuario(cliente);
            if (es) {
                JOptionPane.showMessageDialog(null, "El cliente se ha editado con éxito");
                limpiar();
                txtDocumento5.setEditable(true);
                btnEditar5.setVisible(false);
                btnEliminar5.setVisible(false);
            } else {
                JOptionPane.showMessageDialog(null, "El cliente no se ha podido modificar");
            }
        }
    }//GEN-LAST:event_btnEditar5ActionPerformed

    private void btnEliminar5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminar5ActionPerformed

        if (txtDocumento5.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Vefique que campo de documento sea valido");
        } else {
            String documento = txtDocumento5.getText();
            boolean resp = controladorU.eliminarUsuario(documento);
            if (resp) {
                JOptionPane.showMessageDialog(null, "El cliente ha sido eliminado exitosamente");
                limpiar();
                txtDocumento5.setEditable(true);
                btnEditar5.setVisible(false);
                btnEliminar5.setVisible(false);
            } else {
                JOptionPane.showMessageDialog(null, "No se logró eliminar.\nIntente nuevamente.");
            }
        }
    }//GEN-LAST:event_btnEliminar5ActionPerformed

    private void btnBuscar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscar4ActionPerformed
        if (txtDocuEliminar.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ingrese el número de documento del cliente.\nIntente nuevamente");
        } else {
            String buscado = txtDocuEliminar.getText();

            Cliente busc = (Cliente) controladorU.BuscarCliente(buscado);
            if (busc != null) {
                txtDocumento5.setEditable(false);
                btnEditar5.setVisible(true);
                btnEliminar5.setVisible(true);
                txtDocumento5.setText(busc.getDocumento());
                txtNombre5.setText(busc.getNombre());
                txtTelefono5.setText(busc.getTelefono());
                txtCorreo5.setText(busc.getCorreo());
                txtDireccion5.setText(busc.getDireccion());
                txtContra5.setText(busc.getContrasena());
                txtApellido5.setText(busc.getApellido());
                comboSexo5.setSelectedItem(busc.getSexo());
            } else {
                JOptionPane.showMessageDialog(null, "No se encontró el usuario.\nIntente nuevamente.");
            }
        }
    }//GEN-LAST:event_btnBuscar4ActionPerformed

    private void txtCorrAdicional1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorrAdicional1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorrAdicional1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        limpiar();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtDocuEliminarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDocuEliminarKeyTyped
        new ValidarCampos().validarNumeros(evt);
    }//GEN-LAST:event_txtDocuEliminarKeyTyped

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Cliente cliente = pilaZ.pop();
        pilaY.push(cliente);
        controladorU.eliminarUsuario(cliente.getDocumento());
        
        limpiar();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
     Cliente cliente = pilaY.pop();
     pilaZ.push(cliente);
      controladorU.registrarUsuario(cliente,"cliente.com");
        
        limpiar();
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar4;
    private javax.swing.JButton btnEditar5;
    private javax.swing.JButton btnEliminar5;
    private javax.swing.JButton btnRegistrar5;
    private javax.swing.JComboBox<String> comboSexo5;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator19;
    private javax.swing.JSeparator jSeparator20;
    private javax.swing.JSeparator jSeparator21;
    private javax.swing.JTable tablaClientes;
    private javax.swing.JTextField txtApellido5;
    private javax.swing.JTextField txtContra5;
    private javax.swing.JTextField txtCorrAdicional1;
    private javax.swing.JTextField txtCorreo5;
    private javax.swing.JTextField txtDireccion5;
    private javax.swing.JTextField txtDocuEliminar;
    private javax.swing.JTextField txtDocumento5;
    private javax.swing.JTextField txtNombre5;
    private javax.swing.JTextField txtTelefono5;
    // End of variables declaration//GEN-END:variables
}
