/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vistas.parqueadero;

import controladores.ControladorParking;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelos.Vehiculo;
import util.Lista;

/**
 *
 * @author Asus
 */
public class GestionarVehiculos extends javax.swing.JPanel {

    private DefaultTableModel modell;
    private ControladorParking controlador;

    public GestionarVehiculos() {
        initComponents();
        controlador = new ControladorParking();
        modell = new DefaultTableModel();
        this.tablaVehiculos.setModel(modell);
        modell.addColumn("PLACA");
        modell.addColumn("FECHA DE INGRESO");
        modell.addColumn("TIPO DE VEHICULO");
        modell.addColumn("TARIFA");
        limpiar();

    }

    public ControladorParking getControlador() {
        return controlador;
    }

    public void removerTabla() {

        for (int i = 0; i < modell.getRowCount(); i++) {
            modell.removeRow(i);
        }

    }

    public void limpiar() {

        removerTabla();
        llenarTabla();
        txtEntrada.setText("");
        txtPlaca.setText("");
        txtTipo.setText("");
        txtTarifa.setText("");

        txtTarifa.setEditable(false);
        txtEntrada.setEditable(false);
        txtTipo.setEditable(false);
    }

    public void llenarTabla() {
        removerTabla();
        Lista<Vehiculo> vehiculos = controlador.getVehiculos();
        for (int i = 0; i < vehiculos.Size(); i++) {
            Vehiculo vehi = vehiculos.obtener(i);
            if (vehi != null) {
                String[] info = new String[4];
                info[0] = String.valueOf(vehi.getPlaca());
                info[1] = String.valueOf(vehi.getHoraEntrada());
                info[2] = vehi.getTipo();
                info[3] = String.valueOf(vehi.getPrecioTarifa());

                modell.addRow(info);

            } else {

            }

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel63 = new javax.swing.JLabel();
        txtPlaca = new javax.swing.JTextField();
        jSeparator21 = new javax.swing.JSeparator();
        btnBuscar4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaVehiculos = new javax.swing.JTable();
        txtTarifa = new javax.swing.JTextField();
        txtEntrada = new javax.swing.JTextField();
        txtTipo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setPreferredSize(new java.awt.Dimension(1012, 636));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel63.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        jLabel63.setForeground(new java.awt.Color(0, 0, 0));
        jLabel63.setText("PLACA");
        jPanel4.add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 31, -1, -1));

        txtPlaca.setBorder(null);
        txtPlaca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPlacaKeyTyped(evt);
            }
        });
        jPanel4.add(txtPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 58, 214, -1));
        jPanel4.add(jSeparator21, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 80, 217, 10));

        btnBuscar4.setBackground(new java.awt.Color(0, 153, 153));
        btnBuscar4.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/lupa (1) (1).png"))); // NOI18N
        btnBuscar4.setText("BUSCAR");
        btnBuscar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscar4ActionPerformed(evt);
            }
        });
        jPanel4.add(btnBuscar4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 110, 40));

        tablaVehiculos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaVehiculos);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 191, 960, -1));

        txtTarifa.setBackground(new java.awt.Color(255, 255, 255));
        txtTarifa.setBorder(null);
        jPanel4.add(txtTarifa, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, 180, -1));

        txtEntrada.setBackground(new java.awt.Color(255, 255, 255));
        txtEntrada.setBorder(null);
        jPanel4.add(txtEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 70, 180, -1));

        txtTipo.setBackground(new java.awt.Color(255, 255, 255));
        txtTipo.setBorder(null);
        jPanel4.add(txtTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 110, 180, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("TIPO :");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("FECHA ENTRADA :");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("TARIFA :");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, -1, -1));

        jButton1.setBackground(new java.awt.Color(255, 255, 0));
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("GENERAR TIQUETE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 60, 150, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1012, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 636, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtPlacaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPlacaKeyTyped
        //   new ValidarCampos().validarLetras(evt);
    }//GEN-LAST:event_txtPlacaKeyTyped

    private void btnBuscar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscar4ActionPerformed
        if (txtPlaca.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ingrese el número de placa.\nIntente nuevamente");
        } else {
            String buscado = txtPlaca.getText();

            Vehiculo busc = controlador.buscarVehiculo(buscado);
            if (busc != null) {

                txtEntrada.setText(String.valueOf(busc.getHoraEntrada()));
                txtTarifa.setText(String.valueOf(busc.getPrecioTarifa()));
                txtTipo.setText(busc.getTipo());

            } else {
                JOptionPane.showMessageDialog(null, "No se encontró el vehiculo.\nIntente nuevamente.");
            }
        }
    }//GEN-LAST:event_btnBuscar4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (txtPlaca.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ingrese el número de placa.\nIntente nuevamente");
        } else {
            String buscado = txtPlaca.getText();
            Vehiculo busc = controlador.buscarVehiculo(buscado);
            new Tiquete(busc, this).setVisible(true);
        }

    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar4;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator21;
    private javax.swing.JTable tablaVehiculos;
    private javax.swing.JTextField txtEntrada;
    private javax.swing.JTextField txtPlaca;
    private javax.swing.JTextField txtTarifa;
    private javax.swing.JTextField txtTipo;
    // End of variables declaration//GEN-END:variables
}
